name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches: [source]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build and Publish
        uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.GH_ACTIONS_ACCESS_TOKEN }}
          deploy-branch: master
          working-dir: ./site
